version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mredig/led_controller:latest
    restart: unless-stopped
    ports:
      - 8081:8080
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    group_add:
      - dialout
    command: ["/dev/ttyACM0", "--hostname", "0.0.0.0", "--port", "8080"]
